import Head from "next/head";
import AddTodo from "../../components/AddTodo";
import styles from "../styles/Home.module.css";
import Toggle from "../../components/toggle";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { at, bt } from "../../reducers/todoSlice";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    const todos = localStorage.getItem("todos")
      ? JSON.parse(localStorage.getItem("todos"))
      : [];
    dispatch(at(todos));
  }, [dispatch]);
  return (
    <>
      <Head>
        <title>Todo - APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Toggle />
        <AddTodo />
      </main>
    </>
  );
}
