import Head from "next/head";
import AddTodo from "../../components/AddTodo";
import styles from "../styles/Home.module.css";
import Toggle from "../../components/toggle";

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo - APP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Toggle />
        <AddTodo />
      </main>
    </>
  );
}
